@startuml  Monopoly_Game_class_diagram

Game "dices" *--  Dice : uses

Game --> Board
Board *-- Place

Player *-- Card
Bank *-- Card
Hotel --|> House
SpecialPlace --|> Place
PlaceWithCard --|>Place
PlaceWithCardAndHouses --|>PlaceWithCard
PlaceWithCardAndHouses *-- House
PlaceWithCard -- Card
Game -- Bank
Game -- Player


class Dice{
    +roll()
    +showValue():int
}
'Controller for the game app
class Game{
    -activePlayer:Player
    +movePlayer()
    +nextPlayer()
}
class Board
class Bank
{
    +sell(place:Place, player:Player)
}
class Place{
    +id : int
    +icon : Image
    +name : String

}

class SpecialPlace{}
class PlaceWithCard{}
class PlaceWithCardAndHouses{}

class Player{
    +doYouBuy(p:Place):bool
    +buy(bank:Bank, card:Card)
}
note top
    We can use Visitor pattern
    when creating the ranking
end note
class Card{
    +price : int
    +country:String
    +countrySize:int
}
note right
    We can use Composite pattern
    for countries 
end note
class House
class Hotel


@enduml