@startuml
class Player{
    +balance : int
    +name : String
}
class Bank{
    'we can allow infinite balance in bank
    +balance : int
}
class Game {}

class Board {}
class Place{
    +position:int
}
class Card{}
class House{}
class Hotel{}
class Dice{
    +faceValue():int
}
class Chance{
    +color:String
}

Player --* Game
Bank -- Game
Board -- Game
Card -- Place
Place --* Board
Dice --* Game
House --* Place
House --* Bank
Chance --* Board
Card --* Bank
Card --* Player
Chance --* Player
Hotel --|> House
@enduml