@startuml
Game "dices" *-- Dice
Game -- Board
Board *-- Place
PlaceWithCard -- Card
Player *-- Card
Bank *-- Card
Hotel --|> House
PlaceWithCardAndHouses *-- House
Game -- Bank
Game *-- Player
SpecialPlace --|> Place
PlaceWithCard --|> Place
PlaceWithCardAndHouses --|> PlaceWithCard


class Dice{
    +roll()
    +showValue():int
}
'Controller of the game process'
class Game{
    -activePlayer: Player
    +nextPlayer()
    'implements move activity diagram'
    +moveProcess()
}
class Board{
    +getPlaceOnPosition(p:int):Place
}
class Bank{
    -cashAmmount:int
    +isPlaceOwned(place:Place):boolean
    /' 
        sell - operations:
        increase ammount, 
        remove card from bank,
        invoke buy on player
    '/
    +sell(card:Card, player:Player)
}
class Place {}


class SpecialPlace {
    +acion():void
}
class PlaceWithCard {}
class PlaceWithCardAndHouses {}



class Player{
    -cashAmmount:int
    +position:int 
    +move()
    +doYouBuy(place:Place): boolean
    /' 
        buy - operations:
        decrease ammount, 
        add card
    '/
    +buy(card:Card)
}
class Card
class House
class Hotel

@enduml