@startuml

class Game{}
class Player{
    name:String
    balance :int
}
class Bank{}
class Board{}
class Place{
    position:int
    name:String
}
class Pawn{
    position:int
    color:String
}
class Dice{
    roll():int
}
class Card{
    price:int
}
class Chance{
    info:String
    action():void
}
class House{}
class Hotel{}
class PlaceWithCard{}
class PlaceWithCardAndHouses{}
class SpecialPlace{}


Player --* Game
Pawn -- Player
Pawn --* Board
Dice --* Game
Bank -- Game
Place --* Board
Card -- PlaceWithCard
Chance --* Board
Card --* Player
Card --* Bank
Chance --* Player 
House --* Bank
House --* PlaceWithCardAndHouses
Hotel --|> House
PlaceWithCard --|> Place
PlaceWithCardAndHouses --|> PlaceWithCard
SpecialPlace --|>Place

@enduml