@startuml

class Game{}
class Player{
    name:String
    balance :int
    moveTo(Place):void
    updateBalance(ammount:int):void
    addCard(card:Card):void
    removeCard(card:Card):void
}
class Bank{
    updateBalance(ammount:int):void
    addCard(card:Card):void
    removeCard(card:Card):void
}
class Board{
    newPosition(Player, int[]):Place
}
class Place{
    position:int
    name:String
}
class Pawn{
    position:int
    color:String
}
class Dice{
    roll():int
}
class Card{
    price:int
}
note left    
    country:String
    countrySize:int
    ---
    or new Class Country
end note
class Chance{
    info:String
    action():void
}
class House{}
class Hotel{}
class PlaceWithCard{}
class PlaceWithCardAndHouses{}
class SpecialPlace{
    action():void
}

class UI{
    buyDecision(Player,Place):boolean
}

Player --* Game
Pawn -- Player
Pawn --* Board
Dice --* Game
Bank -- Game
Board -- Game
UI -- Game
Place --* Board
Card -- PlaceWithCard
Chance --* Board
Card --* Player
Card --* Bank
Chance --* Player 
House --* Bank
House --* PlaceWithCardAndHouses
Hotel --|> House
PlaceWithCard --|> Place
PlaceWithCardAndHouses --|> PlaceWithCard
SpecialPlace --|>Place

@enduml